<?php
/* @var $this FullController */
/* @var $model Full */

$this->breadcrumbs=array(
	'Fulls'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Full', 'url'=>array('index')),
	array('label'=>'Create Full', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('full-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Fulls</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'full-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		//'id',
		'idUsuario',
		array('name'=>'consiente','header'=>'Consiente'),
		array('name'=>'afirmacion_sec','header'=>'Cursado Secundaria'),
		array('name'=>'fecha_sec','header'=>'Fecha Secundaria'),
		array('name'=>'centro_sec','header'=>'Centro Secundaria'),
                
		
		array('name'=>'tipo_bach','header'=>'Tipo o Rama Bachillerato'),
            array('name'=>'fecha_bach','header'=>'Fecha Bachillerato'),
		array('name'=>'centro_bach','header'=>'Centro Bachillerato'),
		
		/*'nombre_tituniv',
		'fecha_tituniv',
		'universidad_tituniv',
		'nombre_mast',
		'fecha_mast',
		'universidad_mast',
		'afirmacion_cap',
		'afirmacion_dei',
		'titulo_dei',
		'nivelIngles_idio',
		'nivelFrances_idio',
		'nivelAleman_idio',
		'idiomaOtros_idio',
		'nivelOtros_idio',
		'titulo_titidio',
		'entidad_titidio',
		'from_titidio',
		'to_titidio',
		'programa_ci',
		'nivel_ci',
		'funcion_exnd',
		'time_exnd',
		'from_exnd',
		'to_exnd',
		'funcion_dr',
		'materia_dr',
		'nombreCentro_dr',
		'time_dr',
		'from_dr',
		'to_dr',
		'descripcion_excul',
		'localidad_excul',
		'entidad_excul',
		'from_excul',
		'to_excul',
		'descripcion_exrel',
		'localidad_exrel',
		'entidad_exrel',
		'from_exrel',
		'to_exrel',
		'descripcion_exvol',
		'localidad_exvol',
		'entidad_exvol',
		'from_exvol',
		'to_exvol',
		'tema1_sing',
		'tema2_sing',
		'asistirCursos_sing',
		'limitacionHorario_sing',
		'capacidadEquipo_aut',
		'relacionesPersonales_aut',
		'aptitudesSituaciones_aut',
		'gradoPrepProf_aut',
		'capacidadPlanif_aut',
		'aptitudeRelacio_aut',
		'aperturaTrans_aut',
		'perteneceFS_aut',
		'perteneceGE_aut',
		'preparacionAcad',
		'experienciaDocent',
		'habilidadesPers',
		'gustoJovenes',
		'estiloSalesiano',
		'ilusionVocacion',*/
		
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>
<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'full2-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		//'id',
		'idUsuario',
		/*'consiente',
		'afirmacion_sec',
		'fecha_sec',
		'centro_sec',
		
		'tipo_bach',
		'fecha_bach',
		'centro_bach',*/
                'nombre_tituniv',
		'fecha_tituniv',
		'universidad_tituniv',
		'nombre_mast',
		'fecha_mast',
		'universidad_mast',
		'afirmacion_cap',
		'afirmacion_dei',
		'titulo_dei',/*
		'nivelIngles_idio',
		'nivelFrances_idio',
		'nivelAleman_idio',
		'idiomaOtros_idio',
		'nivelOtros_idio',
		'titulo_titidio',
		'entidad_titidio',
		'from_titidio',
		'to_titidio',
		'programa_ci',
		'nivel_ci',
		'funcion_exnd',
		'time_exnd',
		'from_exnd',
		'to_exnd',
		'funcion_dr',
		'materia_dr',
		'nombreCentro_dr',
		'time_dr',
		'from_dr',
		'to_dr',
		'descripcion_excul',
		'localidad_excul',
		'entidad_excul',
		'from_excul',
		'to_excul',
		'descripcion_exrel',
		'localidad_exrel',
		'entidad_exrel',
		'from_exrel',
		'to_exrel',
		'descripcion_exvol',
		'localidad_exvol',
		'entidad_exvol',
		'from_exvol',
		'to_exvol',
		'tema1_sing',
		'tema2_sing',
		'asistirCursos_sing',
		'limitacionHorario_sing',
		'capacidadEquipo_aut',
		'relacionesPersonales_aut',
		'aptitudesSituaciones_aut',
		'gradoPrepProf_aut',
		'capacidadPlanif_aut',
		'aptitudeRelacio_aut',
		'aperturaTrans_aut',
		'perteneceFS_aut',
		'perteneceGE_aut',
		'preparacionAcad',
		'experienciaDocent',
		'habilidadesPers',
		'gustoJovenes',
		'estiloSalesiano',
		'ilusionVocacion',*/
		
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'full-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		//'id',
		'idUsuario',
		//'consiente',
		//'afirmacion_sec',
		//'fecha_sec',
		//'centro_sec',
		
		//'tipo_bach',
		//'fecha_bach',
		//'centro_bach',
		/*'nombre_tituniv',
		'fecha_tituniv',
		'universidad_tituniv',
		'nombre_mast',
		'fecha_mast',
		'universidad_mast',
		'afirmacion_cap',
		'afirmacion_dei',
		'titulo_dei',*/
		'nivelIngles_idio',
		'nivelFrances_idio',
		'nivelAleman_idio',
		'idiomaOtros_idio',
		'nivelOtros_idio',
		'titulo_titidio',
		'entidad_titidio',
		'from_titidio',
		'to_titidio',
		'programa_ci',/*
		'nivel_ci',
		'funcion_exnd',
		'time_exnd',
		'from_exnd',
		'to_exnd',
		'funcion_dr',
		'materia_dr',
		'nombreCentro_dr',
		'time_dr',
		'from_dr',
		'to_dr',
		'descripcion_excul',
		'localidad_excul',
		'entidad_excul',
		'from_excul',
		'to_excul',
		'descripcion_exrel',
		'localidad_exrel',
		'entidad_exrel',
		'from_exrel',
		'to_exrel',
		'descripcion_exvol',
		'localidad_exvol',
		'entidad_exvol',
		'from_exvol',
		'to_exvol',
		'tema1_sing',
		'tema2_sing',
		'asistirCursos_sing',
		'limitacionHorario_sing',
		'capacidadEquipo_aut',
		'relacionesPersonales_aut',
		'aptitudesSituaciones_aut',
		'gradoPrepProf_aut',
		'capacidadPlanif_aut',
		'aptitudeRelacio_aut',
		'aperturaTrans_aut',
		'perteneceFS_aut',
		'perteneceGE_aut',
		'preparacionAcad',
		'experienciaDocent',
		'habilidadesPers',
		'gustoJovenes',
		'estiloSalesiano',
		'ilusionVocacion',*/
		
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'full-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		//'id',
		'idUsuario',
		//'consiente',
		//'afirmacion_sec',
		//'fecha_sec',
		//'centro_sec',
		
		//'tipo_bach',
		//'fecha_bach',
		//'centro_bach',
		/*'nombre_tituniv',
		'fecha_tituniv',
		'universidad_tituniv',
		'nombre_mast',
		'fecha_mast',
		'universidad_mast',
		'afirmacion_cap',
		'afirmacion_dei',
		'titulo_dei',
		'nivelIngles_idio',
		'nivelFrances_idio',
		'nivelAleman_idio',
		'idiomaOtros_idio',
		'nivelOtros_idio',
		'titulo_titidio',
		'entidad_titidio',
		'from_titidio',
		'to_titidio',
		'programa_ci',
		'nivel_ci',*/
		array('name'=>'funcion_exnd','header'=>'Funcion (Experiencia No Docente)'),
		'time_exnd',
		'from_exnd',
		'to_exnd',
		array('name'=>'funcion_dr','header'=>'Funcion (Experiencia Docente)'),
		'materia_dr',
		'nombreCentro_dr',
		'time_dr',
		'from_dr',
		'to_dr',/*
		'descripcion_excul',
		'localidad_excul',
		'entidad_excul',
		'from_excul',
		'to_excul',
		'descripcion_exrel',
		'localidad_exrel',
		'entidad_exrel',
		'from_exrel',
		'to_exrel',
		'descripcion_exvol',
		'localidad_exvol',
		'entidad_exvol',
		'from_exvol',
		'to_exvol',
		'tema1_sing',
		'tema2_sing',
		'asistirCursos_sing',
		'limitacionHorario_sing',
		'capacidadEquipo_aut',
		'relacionesPersonales_aut',
		'aptitudesSituaciones_aut',
		'gradoPrepProf_aut',
		'capacidadPlanif_aut',
		'aptitudeRelacio_aut',
		'aperturaTrans_aut',
		'perteneceFS_aut',
		'perteneceGE_aut',
		'preparacionAcad',
		'experienciaDocent',
		'habilidadesPers',
		'gustoJovenes',
		'estiloSalesiano',
		'ilusionVocacion',*/
		
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>
<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'full-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		//'id',
		'idUsuario',
		//'consiente',
		//'afirmacion_sec',
		//'fecha_sec',
		//'centro_sec',
		
		//'tipo_bach',
		//'fecha_bach',
		//'centro_bach',
		/*'nombre_tituniv',
		'fecha_tituniv',
		'universidad_tituniv',
		'nombre_mast',
		'fecha_mast',
		'universidad_mast',
		'afirmacion_cap',
		'afirmacion_dei',
		'titulo_dei',
		'nivelIngles_idio',
		'nivelFrances_idio',
		'nivelAleman_idio',
		'idiomaOtros_idio',
		'nivelOtros_idio',
		'titulo_titidio',
		'entidad_titidio',
		'from_titidio',
		'to_titidio',
		'programa_ci',
		'nivel_ci',
		array('name'=>'funcion_exnd','header'=>'Funcion (Experiencia No Docente)'),
		'time_exnd',
		'from_exnd',
		'to_exnd',
		array('name'=>'funcion_dr','header'=>'Funcion (Experiencia Docente)'),
		'materia_dr',
		'nombreCentro_dr',
		'time_dr',
		'from_dr',
		'to_dr',*/
		array('name'=>'descripcion_excul','header'=>'Experiencia Cultural'),
		'localidad_excul',
		'entidad_excul',
		'from_excul',
		'to_excul',
		array('name'=>'descripcion_exrel','header'=>'Experiencia Religiosa'),
		'localidad_exrel',
		'entidad_exrel',
		'from_exrel',
		'to_exrel',
		array('name'=>'descripcion_exvol','header'=>'Experiencia Voluntariado'),
		'localidad_exvol',
		'entidad_exvol',
		'from_exvol',
		'to_exvol',/*
		'tema1_sing',
		'tema2_sing',
		'asistirCursos_sing',
		'limitacionHorario_sing',
		'capacidadEquipo_aut',
		'relacionesPersonales_aut',
		'aptitudesSituaciones_aut',
		'gradoPrepProf_aut',
		'capacidadPlanif_aut',
		'aptitudeRelacio_aut',
		'aperturaTrans_aut',
		'perteneceFS_aut',
		'perteneceGE_aut',
		'preparacionAcad',
		'experienciaDocent',
		'habilidadesPers',
		'gustoJovenes',
		'estiloSalesiano',
		'ilusionVocacion',*/
		
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>
<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'full-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		//'id',
		'idUsuario',
		//'consiente',
		//'afirmacion_sec',
		//'fecha_sec',
		//'centro_sec',
		
		//'tipo_bach',
		//'fecha_bach',
		//'centro_bach',
		/*'nombre_tituniv',
		'fecha_tituniv',
		'universidad_tituniv',
		'nombre_mast',
		'fecha_mast',
		'universidad_mast',
		'afirmacion_cap',
		'afirmacion_dei',
		'titulo_dei',
		'nivelIngles_idio',
		'nivelFrances_idio',
		'nivelAleman_idio',
		'idiomaOtros_idio',
		'nivelOtros_idio',
		'titulo_titidio',
		'entidad_titidio',
		'from_titidio',
		'to_titidio',
		'programa_ci',
		'nivel_ci',
		array('name'=>'funcion_exnd','header'=>'Funcion (Experiencia No Docente)'),
		'time_exnd',
		'from_exnd',
		'to_exnd',
		array('name'=>'funcion_dr','header'=>'Funcion (Experiencia Docente)'),
		'materia_dr',
		'nombreCentro_dr',
		'time_dr',
		'from_dr',
		'to_dr',
		'descripcion_excul',
		'localidad_excul',
		'entidad_excul',
		'from_excul',
		'to_excul',
		'descripcion_exrel',
		'localidad_exrel',
		'entidad_exrel',
		'from_exrel',
		'to_exrel',
		'descripcion_exvol',
		'localidad_exvol',
		'entidad_exvol',
		'from_exvol',
		'to_exvol',*/
		array('name'=>'tema1_sing','header'=>'Conocimiento estilo educativo D.Bosco'),
		array('name'=>'tema2_sing','header'=>'Planteamiento educativo cristiano'),
		array('name'=>'asistirCursos_sing','header'=>'Asistir a Cursos'),
		array('name'=>'limitacionHorario_sing','header'=>'Limitacion Horaria'),/*
		'capacidadEquipo_aut',
		'relacionesPersonales_aut',
		'aptitudesSituaciones_aut',
		'gradoPrepProf_aut',
		'capacidadPlanif_aut',
		'aptitudeRelacio_aut',
		'aperturaTrans_aut',
		'perteneceFS_aut',
		'perteneceGE_aut',
		'preparacionAcad',
		'experienciaDocent',
		'habilidadesPers',
		'gustoJovenes',
		'estiloSalesiano',
		'ilusionVocacion',*/
		
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>
<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'full-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		//'id',
		'idUsuario',
		//'consiente',
		//'afirmacion_sec',
		//'fecha_sec',
		//'centro_sec',
		
		//'tipo_bach',
		//'fecha_bach',
		//'centro_bach',
		/*'nombre_tituniv',
		'fecha_tituniv',
		'universidad_tituniv',
		'nombre_mast',
		'fecha_mast',
		'universidad_mast',
		'afirmacion_cap',
		'afirmacion_dei',
		'titulo_dei',
		'nivelIngles_idio',
		'nivelFrances_idio',
		'nivelAleman_idio',
		'idiomaOtros_idio',
		'nivelOtros_idio',
		'titulo_titidio',
		'entidad_titidio',
		'from_titidio',
		'to_titidio',
		'programa_ci',
		'nivel_ci',
		array('name'=>'funcion_exnd','header'=>'Funcion (Experiencia No Docente)'),
		'time_exnd',
		'from_exnd',
		'to_exnd',
		array('name'=>'funcion_dr','header'=>'Funcion (Experiencia Docente)'),
		'materia_dr',
		'nombreCentro_dr',
		'time_dr',
		'from_dr',
		'to_dr',
		'descripcion_excul',
		'localidad_excul',
		'entidad_excul',
		'from_excul',
		'to_excul',
		'descripcion_exrel',
		'localidad_exrel',
		'entidad_exrel',
		'from_exrel',
		'to_exrel',
		'descripcion_exvol',
		'localidad_exvol',
		'entidad_exvol',
		'from_exvol',
		'to_exvol',
		array('name'=>'tema1_sing','header'=>'Conocimiento estilo educativo D.Bosco'),
		array('name'=>'tema2_sing','header'=>'Planteamiento educativo cristiano'),
		array('name'=>'asistirCursos_sing','header'=>'Asistir a Cursos'),
		array('name'=>'limitacionHorario_sing','header'=>'Limitacion Horaria'),*/
		array('name'=>'capacidadEquipo_aut','header'=>'Trabajo en Equipo'),
		array('name'=>'relacionesPersonales_aut','header'=>'Talente de dialogo'),
		array('name'=>'aptitudesSituaciones_aut','header'=>'Aptitudes Control Situaciones'),
		array('name'=>'gradoPrepProf_aut','header'=>'Grado Preparacion Profresional'),
		array('name'=>'capacidadPlanif_aut','header'=>'Planificacion Tareas ordenada'),
		array('name'=>'aptitudeRelacio_aut','header'=>'Aptitudes Relacion Educativa'),
		array('name'=>'aperturaTrans_aut','header'=>'Apertura sentido Religioso'),
		array('name'=>'perteneceFS_aut','header'=>'Pertenece grupo F.Salesiana'),
		array('name'=>'perteneceGE_aut','header'=>'Pertenece grupo Eclesial'),/*
		'preparacionAcad',
		'experienciaDocent',
		'habilidadesPers',
		'gustoJovenes',
		'estiloSalesiano',
		'ilusionVocacion',*/
		
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>
<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'full-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		//'id',
		'idUsuario',
		//'consiente',
		//'afirmacion_sec',
		//'fecha_sec',
		//'centro_sec',
		
		//'tipo_bach',
		//'fecha_bach',
		//'centro_bach',
		/*'nombre_tituniv',
		'fecha_tituniv',
		'universidad_tituniv',
		'nombre_mast',
		'fecha_mast',
		'universidad_mast',
		'afirmacion_cap',
		'afirmacion_dei',
		'titulo_dei',
		'nivelIngles_idio',
		'nivelFrances_idio',
		'nivelAleman_idio',
		'idiomaOtros_idio',
		'nivelOtros_idio',
		'titulo_titidio',
		'entidad_titidio',
		'from_titidio',
		'to_titidio',
		'programa_ci',
		'nivel_ci',
		array('name'=>'funcion_exnd','header'=>'Funcion (Experiencia No Docente)'),
		'time_exnd',
		'from_exnd',
		'to_exnd',
		array('name'=>'funcion_dr','header'=>'Funcion (Experiencia Docente)'),
		'materia_dr',
		'nombreCentro_dr',
		'time_dr',
		'from_dr',
		'to_dr',
		'descripcion_excul',
		'localidad_excul',
		'entidad_excul',
		'from_excul',
		'to_excul',
		'descripcion_exrel',
		'localidad_exrel',
		'entidad_exrel',
		'from_exrel',
		'to_exrel',
		'descripcion_exvol',
		'localidad_exvol',
		'entidad_exvol',
		'from_exvol',
		'to_exvol',
		array('name'=>'tema1_sing','header'=>'Conocimiento estilo educativo D.Bosco'),
		array('name'=>'tema2_sing','header'=>'Planteamiento educativo cristiano'),
		array('name'=>'asistirCursos_sing','header'=>'Asistir a Cursos'),
		array('name'=>'limitacionHorario_sing','header'=>'Limitacion Horaria'),/*
		'capacidadEquipo_aut',
		'relacionesPersonales_aut',
		'aptitudesSituaciones_aut',
		'gradoPrepProf_aut',
		'capacidadPlanif_aut',
		'aptitudeRelacio_aut',
		'aperturaTrans_aut',
		'perteneceFS_aut',
		'perteneceGE_aut',*/
		'preparacionAcad',
		'experienciaDocent',
		'habilidadesPers',
		'gustoJovenes',
		'estiloSalesiano',
		'ilusionVocacion',
		
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>